# nginx proxy address - http://172.17.0.1:8091

name: stalwart
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: stalwartlabs/mail-server:latest
    pull_policy: always
    container_name: stalwart-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - stalwart
    ports:
      - "172.17.0.1:8091:8080"
      - "25:25/tcp"
      - "465:465/tcp"
      - "587:587/tcp"
      - "143:143/tcp"
      - "993:993/tcp"
      - "4190:4190/tcp"
    environment:
      TZ: ${TZ:-America/New_York}
    volumes:
      - ./volumes/config/stalwart:/opt/stalwart-mail/etc
      - ./volumes/data/stalwart:/opt/stalwart-mail/data

networks:
  stalwart:
    name: stalwart
    external: false
